[tool.ruff]
target-version = "py311"
output-format = "concise"
lint.isort.split-on-trailing-comma = false
lint.select = [
  "ANN001",
  "B",
  "C4",
  "D",
  "E",
  "ERA",
  "F",
  "FURB",
  "I",
  "N",
  "PERF",
  "PGH",
  "PTH",
  "RUF",
  "SIM",
  "T",
  "TRY",
  "W",
]
lint.ignore = [
  "B008",
  "D205",
  "E501",
  "F403",
  "SIM115",
  "RUF006",
  "RUF008",
  "RUF012",
  "TRY0",
]
lint.pydocstyle.convention = "google"