name: Deploy to staging

on:
  push:
    branches:
      - 'r/*'

concurrency:
  group: deploy-staging
  cancel-in-progress: false

env:
  FLY_API_TOKEN: ${{ secrets.STG_FLY_API_TOKEN }}
  CP_WEB_URL: https://cloud.reflexcorp.run/
  CP_BACKEND_URL: https://cloud-29f4f535-4fb8-48b9-8b55-2000f2782aee.fly.dev/

jobs:
  deploy:
    name: Deploy to Reflex Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Update Reflex CLI
        run: pip install reflex-hosting-cli -U

      - name: Deploy to Reflex
        id: deploy
        run: |
          reflex deploy --project ${{ secrets.STG_PROJECT_ID }} --token ${{ secrets.STG_TOKEN }} --no-interactive
