name: pre-commit

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  pre-commit:
    name: Pre-commit
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install UV
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          activate-environment: true

      - name: Install Requirements
        run: uv sync

      - run: pre-commit run --all-files --show-diff-on-failure --color=always
